# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_docentes3?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=sasha
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Configuración de los Admins (Correos Reales)
app.admin.emails=admin@sashabf.com,direccion@sashabf.com

# Configuración del servidor de correo 
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=22d72389b1c9e8
spring.mail.password=2530a8c036a10c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


